name: Changed tf files
on: push
jobs:
  build_a_ting:
    name: Running CI format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["terraform/another_ec2","terraform/ec2"]
    env:
      TERRAFORM_VERSION: 0.11.8
    steps:
    - name: 'check it out'
      uses: actions/checkout@v2

    - name: Cache Terraform Install
      id: cache-terraform-install
      uses: actions/cache@v1
      with:
        path: ~/.terraform
        key: ${{ env.TERRAFORM_VERSION }}

    - name: Add terraform to path
      run: |
        echo "::add-path::~/.terraform"

    - name: Instally terraform
      if: steps.cache-terraform-install.outputs.cache-hit == 'false'
      run: |
        curl -s -S -L -o /tmp/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
        sudo unzip -o -d ~/.terraform/ /tmp/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip

    - name: Run terraform version check
      run: |
        which -a terraform
        /usr/local/bin/terraform --version
        echo $PATH
        terraform --version
