name: 'Terraform GitHub Actions'
on:
  - pull_request
jobs:
  matrix_name:
    name: "Running CI on ${{ matrix.dir }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ terraform/another_ec2, terraform/ec2 ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.11.8
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ matrix.dir }}
      - name: 'Terraform fmt'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.11.8
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ matrix.dir }}
